; FERM-3.mmd
; Fermentador continuo con inhibición por sustrato


; EQUATIONS

; Differential
X' = -D*X+rX
S' = D*(S0-S)+rS

; Algebraic
rX = U*X; g/(L*h)
U = UM*S/(KS+S+S^2/KI); 1/h
rS = -rX/Y; g/(L*h)


; PARAMETERS

; Constants
UM = 0.53; 1/h
KS = 0.12; g/L
KI = 2.2; g/L  
Y = 0.5; ad
S0 = 5; g/L
D = 0.25; 1/h

; Initial conditions
INIT X = 2; g/L
INIT S = 0.5; g/L

; Integration
STOPTIME = 100 ;h
DT = 0.01 ;h
