; FERM-2.mmd
; Fermentador continuo


; EQUATIONS

; Differential
X' = -D*X+rX
S' = D*(S0-S)+rS
P' = -D*P+rP

; Algebraic
rX = U*X; g/(L*h)
U = UM*S/(KS+S); 1/h
rS = -rX/Y; g/(L*h)
rP = (k1+k2*U)*X; g/(L*h)
PROD = D*P; g/(L*h)


; PARAMETERS

; Constants
S0 = 10; g/L
D = 0.1; 1/h
UM = 0.3; 1/h
KS = 0.1; g/L
k1 = 0.03; 1/h
k2 = 0.08; ad
Y = 0.8; ad

; Initial conditions
INIT X = 1; g/L
INIT S = 10; g/L
INIT P = 0; g/L

; Integration
STOPTIME = 80 ;h
DT = 0.01 ;h
