; SEP-1.mmd
; Extracción líquido-líquido


; EQUATIONS

; Differential
Cw' = (Fw*(Cw0-Cw)-Q)/Vw   
Co' = (Fo*(Co0-Co)+Q)/Vo 

; Algebraic
Q = KLa*(Cw-Co/Pow)*(Vw+Vo); g/h


; PARAMETERS

; Constants
Vw = 10; L
Vo = 10; L
Cw0 = 1; g/L
Co0 = 0; g/L
Fw = 1; L/h
Fo = 3; L/h
Pow = 0.8; ad
KLa =  2.5; 1/h

; Initial conditions
INIT Cw = 1; g/L
INIT Co = 0; g/L

; Integration
STOPTIME = 50; h
DT = 0.01; h