; SEP-1.mmd
; Extracción líquido-líquido


; EQUATIONS

; Differential
X' = (L*(X0-X)-Q) /VL   
Y' = (G*(Y0-Y)+Q) /VG 

; Algebraic
Q = KLa*(X-Y/m)*(VL+VG); g/h


; PARAMETERS

; Constants
VL = 10; L
VG = 10; L
X0 = 1; g/L
Y0 = 0; g/L
L = 1; L/h
G = 3; L/h
m = 0.8; ad
KLa =  2.5; 1/h

; Initial conditions
INIT X = 1; g/L
INIT Y = 0; g/L

; Integration
STOPTIME = 50 ;h
DT = 0.01 ;h
